import logging
from print_label import print_shipping_label

# Set up logging
logging.basicConfig(level=logging.INFO)

# Sample base64 ZPL string (replace this with your actual base64 ZPL string)
sample_base64_zpl = "XlhBXkNGLDAsMCwwXlBSMTJeTUQzMF5QT0leQ0kxM15MSDAsMjAKXkZPMTIsMTI0XkdCNzU1LDIsMl5GUwpeRk8xMiwzOTBeR0I3NzcsMiwyXkZTCl5GTzMyLDNeQWROLDAsMF5GV05eRkheRkRGUk9NOl5GUwpeRk8zMiwxOV5BZE4sMCwwXkZXTl5GSF5GRERhbmllbCBXb29kbWFuXkZTCl5GTzMyLDM3XkFkTiwwLDBeRldOXkZIXkZERGF2aW5jaV5GUwpeRk8zMiw1NV5BZE4sMCwwXkZXTl5GSF5GRDE0RSBFYXN5IFN0cmVldCBCb3VuZCBCcm9vaywgTkpeRlMKXkZPMzIsNzNeQWROLDAsMF5GV05eRkheRkQwODgwNV5GUwpeRk8zMiwxMDleQWROLDAsMF5GV05eRkheRkRVUyBeRlMKXkZPMjI0LDNeQWROLDAsMF5GV05eRkheRkQxNzMyODAzMzczM15GUwpeRk8yOCw3NDJeQTBOLDI0LDI0XkZXTl5GSF5GRFRSSyNeRlMKXkZPMjgsODAwXkEwTiwyNywzMl5GV05eRkheRkReRlMKXkZPMTM2LDcxMl5BME4sMjcsMzZeRldOXkZIXkZEXkZTCl5GTzMyLDkxXkFkTiwwLDBeRldOXkZIXkZEQm91bmQgQnJvb2sgTkogMDg4MDVeRlMKXkZPNDc4LDNeQWROLDAsMF5GV05eRkheRkRTSElQIERBVEU6IDEySlVMMjReRlMKXkZPNDc4LDE5XkFkTiwwLDBeRldOXkZIXkZEQUNUV0dUOiAzLjAwIExCXkZTCl5GTzQ3OCwzN15BZE4sMCwwXkZXTl5GSF5GRENBRDogMDAwMDAwMC9XU1hJMzYwMF5GUwpeRk80NzgsOTFeQWROLDAsMF5GV05eRkheRkRCSUxMIFNFTkRFUl5GUwpeRk8zOSwxMzZeQTBOLDM5LDM5XkZ"

# Add padding to the base64 string if necessary
missing_padding = len(sample_base64_zpl) % 4
if missing_padding:
    sample_base64_zpl += '=' * (4 - missing_padding)

# Specify the printer name
printer_name = "Zebra_Technologies_ZTC_GK420d"

# Call print_shipping_label with the base64 ZPL string, is_zpl=True, and the specified printer name
# print_shipping_label(sample_base64_zpl, is_zpl=True, printer_name=printer_name)